### PR TITLE
Hash the HTMLATTRIBUTES and push other to 'attributes' attribute

### PR DESCRIPTION
**Pull request by jiayp**
Clean the log and reopen the PR.

before this PR
````
ul({ class: 'dropdown-menu', attributes: {role: 'menu', 'aria-labelledby': 'myid'} }, content)
````
after this PR
````
ul({ class: 'dropdown-menu', role: 'menu', aria_labelledby: 'myid' }, content)
````

### CODE REVIEW

**Comment by jgaskins** [comment]
I've been working on performance a bit lately and I think one of the changes I made last night is going to cause a merge conflict with this.

I think I also need to determine whether moving camelizing to the component is the best idea — you're right that ideally it should match `SVGComponent`, but I wonder if it's the right place. With `SVGComponent`, I put it in there mainly because it was the only way I could think of to make it work with hyphenated attributes. I'm pretty sure the people who designed the JS DOM API and the people who designed the JS SVG API are not the same people. :-)

Maybe instead of camelizing attributes, the `SVGComponent` hash could just transform the hyphenated ones. I need to think about this more.

**Comment by jgaskins** [comment]
By the way, I really appreciate how patient you've been here. I realize I've told you no a lot over the past couple days and you're still trying to contribute based on the feedback I've given. Just wanted you to know I appreciate that. :+1:

**Comment by jiayp** [comment]
@jgaskins your works on Clearwater is great. Clearwater is awesome!It is fast and with clean code.
I will use this in our new website and I want to improve it with you and others too. 

Thanks your patient feedbacks to my poor english stuffs.

**Comment by jiayp** [comment]
By the way, a BootStrap example here:
`<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">`

`role` and `aria-*` both not standard HTML properties,How should we handle this?
`div({class: 'modal fade', attributes: {role: 'dialog', 'aria-hidden': true}})`
This will work on before this PR,but people need know exactly what is standard HTML properties what not.

**Comment by jgaskins** [comment]
I wonder if we could store only specific things in the `attributes` sub-hash during sanitization.

**Comment by jgaskins** [comment]
The more I think about this, because the DOM API is so weird, we might want to try to find a better abstraction for the differences between DOM properties and HTML attributes. The fact that there's a difference at all is silly, but we do need to support both in a way that is both performant and relatively friendly to the person using it.

For example, it looks like the only way to use `role` and `aria-*` attributes is to set them with `setAttributes` in JS, which is done with the `attributes` hash in Ruby. However, setting attributes won't modify some `input` elements, such as to check a checkbox programmatically — this _must_ be done through properties.

Since we need to support both, the options seem to be:

1. pass two hashes: one for properties and one for attributes
  - Pros:
    - allows access to both
    - can omit attributes if not needed, similar to how you can omit properties now if you just want content
  - Cons
    - complicates the tag methods significantly
    - when passing only attributes, must specify empty hash or `nil` for properties
2. manage which keys need to go in properties and attributes, funneling each key/value pair into the appropriate hash (what this PR appears to be intended to do)
  - Pros:
    - completely encapsulates properties/attributes
    - it works just like in HTML
  - Cons:
    - potential for huge performance hit
    - significantly increases internal complexity
3. wrap the attributes hash within the properties hash (as is currently the case)
  - Pros:
    - same as pros of number 1, plus …
    - no need to add an argument to the method
  - Cons:
    - must specify `attributes` key when only passing HTML attributes

Although it's a little inconvenient, number 3 seems to be the best choice to me.

**Comment by jgaskins** [comment]
Going to go ahead and close this one down for now. I'd be happy if someone has a better abstraction for the difference between DOM properties and HTML attributes because doing things like `{ attributes: { "aria-label": "My Label" } }` is pretty awkward, but I don't think this is the right way to go.

I really appreciate the effort, though!

**Pull request closed without merging**
