### PR TITLE
improve svg support

### PR DESCRIPTION
**Pull request by jiayp**
`
svg(class: 'mysvg', markerHeight: 10, marker_end: "url(#arrow)")
`
get 
`
<svg class='mysvg' markerHeight=10 marker-end="url(#arrow)" ></svg>
`
Is there better solution for property name convert?

### CODE REVIEW

**Comment by jgaskins** [comment]
SVG is hard because not some attributes are hyphenated and some are camel-cased. So I'm not sure hyphenating all attributes is the right way forward with that. However, I'm glad you pointed out hyphenated keys here, because I hadn't noticed that the SVG JS API didn't camel-case them the way the DOM JS API does. I suppose if I'd scrolled further down in [the spec](http://www.w3.org/Graphics/SVG/WG/wiki/Simple_SVG_API) I would've seen examples of them. :-)

I think what we might need to do there is similar to what we did with the SVG tag names and for the same reason: use a hash to determine the JS property name from the snake-cased Ruby version. In the meantime, you can still specify a hyphenated one like this: `svg("marker-end": "url(#arrow)")`. This is valid Ruby code, even in MRI. :-)

When I checked, regardless of whether I used `class` or `className`, it's not getting the `class` attribute to appear in the rendered DOM, even when doing it in the JS console in the browser. I'm not sure what's going on there.

**Comment by jiayp** [comment]
@jgaskins `svg("marker-end": "url(#arrow)")`is acceptable.

`class` and `class_name` in svg both can't get correct result, because `Component.sanitize_attributes` will change `class` to `class_name` then to `className` and svg has not the attribute 'className` and do not turn it to svg attribute.
I fix it ,but don't know is it the correct way.
https://github.com/jiayp/clearwater/commit/bfab19605c3d0e14c893de2e440cd25490d77ff9

**Comment by jgaskins** [comment]
@jiayp Setting the `class` property with the JS SVG API didn't set the `class` attribute in the rendered markup, though. Have you verified this PR actually sets the `class` attribute in the rendered SVG markup?

**Comment by jiayp** [comment]
@jgaskins Yes,it set the class attribute in chrome.Have not verify other browsers.

**Comment by jgaskins** [comment]
Well, looks like SVG is just really weird. Setting the `class` property via the JS API (highlight it in web inspector, then run `$0.class = 'mysvg'` in the console) does nothing. It _does_ list a `className` property, though.

I'm not sure this PR is the best way to solve it, unfortunately. Given that about half of the SVG attributes are hyphenated and the other half are camel-cased, I think the best way forward is to have a hash of attributes that translate one set of attributes to another and for `SVGComponent` not to use `Component`'s sanitization.

**Comment by jiayp** [comment]
@jgaskins I revert the sanitization changes and just use the `svg("marker-end": "url(#arrow)")` now.

**Comment by jgaskins** [comment]
I'm not sure updating `Component.sanitize_attributes` to suit `SVGComponent` is the right solution, though. SVG components seem to have different attribute-sanitization needs than DOM components due to the differences in their property formats. I think `SVGComponent` needs its own sanitizer. I'll go ahead and write it unless you want to.

**Comment by jgaskins** [comment]
Fixed in ae0eef0d2fb5d0f505f6e460292852053c56717f and released 1.0.0.beta4.

**Comment by jgaskins** [comment]
Specifically, check out changes in [the spec](https://github.com/clearwater-rb/clearwater/commit/ae0eef0d2fb5d0f505f6e460292852053c56717f#diff-bb5399aa2e9f30cc6a76563b6d2a06f3). I used your case in the spec example. :-)

**Pull request closed without merging**
