### PR TITLE
Add <webview> element

### PR DESCRIPTION
**Pull request by eric-khoury**

### CODE REVIEW

**Comment by jgaskins** [comment]
@eric-khoury I've never heard of this element. Is this what you're looking to be able to do: https://developer.chrome.com/apps/tags/webview

**Comment by eric-khoury** [comment]
@jgaskins Yes, sorry for the lack of explanation. I was playing around with the framework using an existing project and while implementing some views to be rendered by components, one in which I use a webview, I realized it wasn't an available tag. This might still be a bit of an edge case tho :)

**Comment by jgaskins** [comment]
Is it a Chrome-specific thing? I'm not sure about including first-class support for browser-specific rendering, but at the very least it does seem to indicate that maybe there should be first-class support for adding your own element types other than copy/pasting the implementation of the rest. Right now, these methods are added dynamically at load time, but there's no way to change what's defined after that. I'll file an issue for that.

Otherwise, for the time being, you should just be able to do `tag('webview', attributes, content)`. I'll have to think about this some more. Feel free to talk more about it, though, so I can understand what this is for (besides Chrome apps).

**Comment by jegt** [comment]
I can explain a bit more what we're doing. We have an Electron based desktop app that we are in the process of converting from opal+jquery to clearwater. I expect that there might be some more issues popping up in the future but so far it has gone well.

**Comment by jgaskins** [comment]
Did you just go ahead with the `tag('webview', attributes, content)` method?

**Comment by eric-khoury** [comment]
Yep, that works fine for now, thanks. I think it's makes sense to not include support for it, since it's a very chrome specific thing.

**Comment by jgaskins** [comment]
:+1: Cool, just wanted to make sure that was all good. :-)

**Pull request closed without merging**
