### PR TITLE
Add AsyncRender component

### PR DESCRIPTION
**Pull request by jgaskins**
This proposal for an `AsyncRender` component is intended for apps that expect to generate large amounts of DOM changes in a single render. It uses `requestAnimationFrame` to delay updating the subtree (on both mount and update) until the following frame. This lets the rest of the UI update itself and saves itself and all its descendants for later.

In effect, it splits the render up into multiple diff/patch cycles.

### Example

```ruby
def render
  div([
    h1('Async Render Demo'),
    Clearwater::AsyncRender.new(div('This part is delayed.')),
    Clearwater::AsyncRender.new(MyLargeComponent.new),
  ])
end
```

In this example, the inner `div` and the `MyLargeComponent` instance are not inserted into the DOM until the following frame. The example is to show that you can use either components or regular vdom nodes. On subsequent renders, the updates will be delayed one frame, as well.

Note: this is not intended to be used at the same level of the DOM tree as hundreds of other renders. That is, don't build a giant list of `AsyncRender` components. Instead, you should wrap the parent element/component inside an `AsyncRender`.

I'm kind of excited about this because the React team has been talking about this concept as "partial diffing" for a while. They don't have it implemented yet AFAIK, and I don't think it can't be implemented inside a component like this PR uses — the React reconciler can't replace the top-level node. The closest I've been able to get it in React is [this pen](https://codepen.io/jgaskins/pen/Kaboxg), which has to wrap the child nodes inside an element of its own.

### CODE REVIEW

**Comment by jgaskins** [comment]
Now that I think about it, maybe we should scope it within the `Clearwater::Component` namespace. Then, when including the mixin, you can reference `AsyncRender` inside your component without name spacing it under anything.

**Comment by johnsusi** [comment]
Interesting. We could probably use this in our app. I will let you know how it works out!

Will it discard queued renders if the main ui updates itself before the async renders have started?

**Comment by jgaskins** [comment]
@johnsusi Your app is specifically one of the scenarios I had in mind when I wrote this. I remember @jegt saying a while back that first renders are sometimes a bit slow if there's a lot of data, making things just look blank for a few hundred milliseconds. I figured you might be able to wrap that component in one of these. It won't stop the browser from locking while that whole tree is calculated, but it'll get _something_ on the screen before that happens.

> Will it discard queued renders if the main ui updates itself before the async renders have started?
I don't know if this would actually happen, tbh. :-) Since the delayed render happens on the next animation frame and Clearwater rendering _also_ waits until the next animation frame, even if you trigger a render here, it shouldn't happen until _after_ the next one occurs.

I've tested this out by running `call` inside both an outer and inner component (as in, if `Outer` renders `AsyncRender.new(Inner.new)`, I tried a call in each one and also in both at the same time) and I couldn't trigger a render-time error.

I'd love to hear any feedback you've got on this, both from a functionality and ergonomics perspective.

**Comment by jgaskins** [comment]
Found an issue with this when using recursive rendering here. Given the following component:

```ruby
class Data
  include Clearwater::Component

  attr_reader :rows

  # @param rows [Array<Array<#to_s>>] 2-dimensional array of values
  def initialize rows
    @rows = rows
  end

  def render
    return if rows.empty?

    chunk_size = 20

    Clearwater::AsyncRender.new(
      div([
        rows.take(chunk_size).map { |row|
          div({ class: 'row' }, row.map { |cell|
            div({ style: cell_style }, cell)
          })
        },
        Data.new(rows.drop(chunk_size)),
      ])
    )
  end

  def cell_style
    # ...
  end
end
```

At a high level, this component divides the data it receives into chunks, renders part of it now, and renders the rest in the next frame, which then also chunks the data, recursively until all data is rendered. It's presented as a table, but made out of `div`s because tables have a strict hierarchy of tag types.

Since regular components have their `render` methods called during vdom generation, this generates the entire tree up front, causing a pause when re-rendering a huge number of rows. My benchmark case had 10k rows of 10, which took 1.6 seconds to render the first frame. Granted, that's pretty great for 110k elements, but it highlighted a flaw.

We need a way to delay generating lower levels of the tree, which can't occur in this case if we simply take a value to delay rendering. I think taking a block would be better here:

```ruby
Clearwater::AsyncRender.new {
  div([
    # ...
  ])
}
```

This also highlights the fact that we can't take an array; you _must_ return a single element. I wanted to get some feedback on this before changing it to make sure I'm not just being pathological here. :-)

**Comment by johnsusi** [comment]
@jgaskins how about both? manually creating an AsyncRender keeps current behaviour but provide a helper method called async_render (or something similar) that takes a block for deferred rendering.

I have been bitten by this behaviour before and would not mind if all rendering happened at the same time. (i.e. builtin `tag` helpers do not expand their children on creation but when rendering).

**Comment by jgaskins** [comment]
> i.e. builtin tag helpers do not expand their children on creation but when rendering

This could probably be done (at least for components), but might have to wait until 2.0 or something because it could cause breaking changes and we should've already released 1.0 by now (been at `1.0.0.rc#` for like 6 months). I'll open an issue for that.

I really do like the idea of an `async_render` method on `Component` to simplify this:

```ruby
async_render { Whatever.new }
```

Would probably make sense not to load `AsyncRender` by default (to keep the default payload small) and display an error here unless it's loaded.

**Comment by jgaskins** [comment]
Added a `Component#async_render` method when you `require 'clearwater/async_render'`. Works really well. For example, here's an example component that renders colorful bars:

```ruby
require 'clearwater/async_render'
NestedRender = Struct.new(:count) do
  include Clearwater::Component

  def render
    return if count.zero?

    div([
      div(style: {
        background_color: "##{rand(16 ** 6).to_s(16).rjust(6, '0')}",
        height: '20px',
        width: '200px',
      }),
      async_render { NestedRender.new(count - 1) },
    ])
  end
end
```

It can be rendered with `NestedRender.new(count)` (`count` = the number of times to render itself). You can watch it render each one. It's really neat.

**Pull request merged**
